import fs from 'fs';
import path from 'path';

const pkgPath = path.resolve('package.json');
// const outPath = path.resolve('version.js');
const outPathDist = path.resolve('dist/version.js');

// Load package.json
const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8'));

// Create JS file
const content = `// Auto-generated by create-version.js
export default {
  name: ${JSON.stringify(pkg.name)},
  version: ${JSON.stringify(pkg.version)},
  homepage: ${JSON.stringify(pkg.homepage)}
}`;

// fs.writeFileSync(outPath, content, 'utf-8');
fs.writeFileSync(outPathDist, content, 'utf-8');

console.log('✅ Created', outPathDist);
